version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pré build phase - Caso houver necessidade"
  build:
    commands:
      - echo "Building"
      - mvn clean compile war:war
  post_build:
    commands:
      - echo "movendo os arquivos"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war