version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pré build pahase"
  build:
    commands:
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "movendo os arquivos"
      - av target/*.war ./ROOT;war
artifacts:
  files:
    - ROOT.war